### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by bla-ke**
Hello!

I translated EteSync, because I noticed that the translation wasn't very good and it had a lot of errors/not translated strings. Hope it can be merged.

The best wishes,
Daria.

### CODE REVIEW

**Comment by tasn** [comment]
Hey Daria,

Thank you very much! Looks good, just needs two minor changes:
1. Please remove the items with ```translatable="false"```, those are not meant to be translated.
2. Please remove the copyright notice, as it's not relevant for this file, which you created.

Thanks again, and looking forward to merging this!

Also, would it be OK by you if I list you as a contributor on https://www.etesync.com/about/ once this gets merged?

Thanks,
Tom.

**Comment by bla-ke** [comment]
Hello Tom,

I've just updated this file:
1. Removed the strings with `translatable="false"`.
2. Removed the copyright notice.

Yeah, it would be OK, but I used the old strings and I think that the previous translator should be listed too (@oskarjakiela).

Regards,
Daria.

**Comment by tasn** [comment]
Oh Github, whey can't I still mark it as merged manually? :(

Thanks Daria, it's in! How would you like me to list you there? I mean, as "Daria (bla-ke)", "bla-ke" any other variation?

As for the old translation: it was translated by him for davdroid, on which this project is based on, and to whom I've already given blanket credit (to avoid having to track people and ask each). Oskar, would you be OK with me adding you to the about page?

**Comment by bla-ke** [comment]
Aaah, nobody knows :(

I think that if everybody uses their own names and surnames, I should too. Just "Daria Szatan" will be ok. I'm not gonna to break this rule, and, of course I don't have any problems with using it :).

Oh, I understand, but unfortunately GitHub haven't seen him (Oskar) since... Well, a lot of time. We will see that he's going to read mails or not. I visited his website, but it's closed (?) or something else. If you want to, I can find him and ask about it 🤔 .

**Comment by tasn** [comment]
I too care a lot about correct attribution, but if you ask me, you are taking it too far. :)

He is already listed as a contributor (on Github), as can be seen here: https://github.com/etesync/android/graphs/contributors

In addition, while I'm happy to also list people who've indirectly helped EteSync (like for example, contributing to davdroid, or libs we use, and as you can see, we have such attribution in the app's about page), the etesync about page was meant to single out people who contributed to EteSync directly because it shows they care about EteSync specifically.

As I said though, I'm happy to list him if he consents, I just don't think you should waste your time trying to locate him.

Just to make it explicit from EteSync too: thanks @oskarjakiela for your contribution!

**Comment by bla-ke** [comment]
I used this list of contributors to find out who has translated it 😊.

I know it, without contributors to davdroid, EteSync wouldn't exist today. That's what I love in OpenSource projects - if you're helping one bigger source of application, you're also helping others. I'm happy about that I translated EteSync, I love to do it with my free time during the weekend. I can study other languages too, which is very helpful, because since I've started to translate applications (and comics, too) and contact with other users, I'm much more better in using English than year ago. I also feel that I can belong to something, I can help others.

If he checks his email regularly, he should get a mail. We will just wait 😉.

Thank you again for everything!

**Comment by tasn** [comment]
Yeah, open source is great. :)

Oskar: cool, keep me posted.

Thank you too!

**Comment by tasn** [comment]
Released a version with your translation included.

Thanks again!

**Pull request closed without merging**
