### PR TITLE
dark theme is working

### PR DESCRIPTION
**Pull request by jahway603**
The colors might need some re-work, as there are still variable names named incorrectly, but regardless now this app has a Dark Theme! This is important for Visual Accessability. This will resolve Issue #144 too.

### CODE REVIEW

**Comment by tasn** [comment]
Yay! I'm currently traveling without the ability to test it, but I'll be able to test in a week! Is it ready?

**Comment by jahway603** [comment]
I believe it's ready, which is why I created the PR :+1: As I stated before, the colors might need some re-work by a more visual person than myself, but I can now look at the app without having any eye strain, which is great news.

**Comment by jahway603** [comment]
@tasn do I need to do anything else to get this dark theme in the Etesync Android app?

**Comment by tasn** [comment]
Nothing else, sorry I haven't tested it yet. I have time on my calendar for this week. Sorry again!

**Comment by tasn** [comment]
Sorry for being slow! It looks great, I just noticed two issues that need fixing:
1. There's a white background when going to journal -> change -> raw (and also non-raw). Just need to make the background dark.
2. When you go to login/signup - the username and password hints don't show when the fields are focused. Not the end of the world if not easy to fix.

Thanks a lot for this, and apologies again for being slow. I'm very excited about getting this one in!

**Comment by tasn** [comment]
Maybe it's not actually using the theme?

**Comment by jahway603** [comment]
Now the "journal -> change" background color will match the selected theme (on both raw and non-raw).

I'm not sure how to fix this though: "When you go to login/signup - the username and password hints don't show when the fields are focused."

**Comment by tasn** [comment]
> I'm not sure how to fix this though: "When you go to login/signup - the username and password hints don't show when the fields are focused."

It's OK, it's not a blocker. I'll merge and release in a bit.

**Comment by tasn** [comment]
I gave it some more testing and:
1. The background is not fixed for me there - is it really fixed for you?
2. It's not persisted across app restarts. So if I change to night, force close the app, open it again, it goes back to the light theme even though "night" is still selected in the settings.

**Comment by jahway603** [comment]
Alright. That's strange that the background is not fixed for you - I'm testing on an Android 8 device, what version are you testing on?

I'm also having the same issue you describe with the theme not persisting across app restarts. I had not tested this, but I'll work on fixing it.

**Comment by tasn** [comment]
> Alright. That's strange that the background is not fixed for you - I'm testing on an Android 8 device, what version are you testing on?

I'm not sure, as I don't have my test phone next to me at the moment, but I want to guess Android 9, maybe 10.

**Comment by jahway603** [comment]
Have not had a chance to work on this further but wanted to add a note that [upstream's davx5](https://github.com/bitfireAT/davx5-ose/), which this code is based upon, does have a fully functional dark theme which I will be exploring (when I get the time again) to see why my changes were not staying persistent.

**Comment by tasn** [comment]
We diverged quite a bit from our davx5 origins, but the theme should be mostly the same! Let me know!

**Pull request closed without merging**
